# Test: UI ve screen language extraction
# Bu dosya, arayüzde geçen Settings, History, Save, Load gibi metinlerin parser tarafından yakalanıp yakalanmadığını test eder.

screen test_ui_screen():
    text "Settings"
    textbutton "History"
    vbox:
        text "Save"
        text "Load"
    frame title "Options"
    window title "Main Menu"
    label "Help"
    textbutton _("Credits")
    textbutton "Quit"
    textbutton _("Continue")
    textbutton "Resume"
    textbutton "Preferences"
    textbutton "Language"
    textbutton "Gallery"
    textbutton "Return"
    textbutton "Back"
    textbutton "Auto"
    textbutton "Skip"
    textbutton "Start"
    textbutton "End"
    textbutton "Replay"
    textbutton "Extra"
    textbutton "Achievements"
    textbutton "CG Gallery"
    textbutton "Music Room"
    textbutton "Scene List"
    textbutton "Settings"
    textbutton "Config"
    textbutton "About"
    textbutton "Exit"
    textbutton "Close"
    textbutton "Open"
    textbutton "Apply"
    textbutton "Reset"
    textbutton "Default"
    textbutton "Fullscreen"
    textbutton "Windowed"
    textbutton "Sound"
    textbutton "Voice"
    textbutton "Music"
    textbutton "Display"
    textbutton "Screen"
    textbutton "Resolution"
    textbutton "Brightness"
    textbutton "Contrast"
    textbutton "Gamma"
    textbutton "Saturation"
    textbutton "Sharpness"
    textbutton "Language"
    textbutton "English"
    textbutton "Turkish"
    textbutton "Japanese"
    textbutton "Korean"
    textbutton "Chinese"
    textbutton "Spanish"
    textbutton "French"
    textbutton "German"
    textbutton "Italian"
    textbutton "Russian"
    textbutton "Polish"
    textbutton "Portuguese"
    textbutton "Czech"
    textbutton "Romanian"
    textbutton "Hungarian"
    textbutton "Greek"
    textbutton "Bulgarian"
    textbutton "Ukrainian"
    textbutton "Indonesian"
    textbutton "Malay"
    textbutton "Hebrew"
    textbutton "Back to Menu"
    textbutton "Return to Game"
    textbutton "Continue Game"
    textbutton "Load Game"
    textbutton "Save Game"
    textbutton "Quick Save"
    textbutton "Quick Load"
    textbutton "Auto Save"
    textbutton "Auto Load"
    textbutton "Settings"
    textbutton "Options"
    textbutton "Preferences"
    textbutton "Help"
    textbutton "Credits"
    textbutton "About"
    textbutton "Exit"
    textbutton "Close"
    textbutton "Open"
    textbutton "Apply"
    textbutton "Reset"
    textbutton "Default"
    textbutton "Fullscreen"
    textbutton "Windowed"
    textbutton "Sound"
    textbutton "Voice"
    textbutton "Music"
    textbutton "Display"
    textbutton "Screen"
    textbutton "Resolution"
    textbutton "Brightness"
    textbutton "Contrast"
    textbutton "Gamma"
    textbutton "Saturation"
    textbutton "Sharpness"
    textbutton "Language"
    textbutton "English"
    textbutton "Turkish"
    textbutton "Japanese"
    textbutton "Korean"
    textbutton "Chinese"
    textbutton "Spanish"
    textbutton "French"
    textbutton "German"
    textbutton "Italian"
    textbutton "Russian"
    textbutton "Polish"
    textbutton "Portuguese"
    textbutton "Czech"
    textbutton "Romanian"
    textbutton "Hungarian"
    textbutton "Greek"
    textbutton "Bulgarian"
    textbutton "Ukrainian"
    textbutton "Indonesian"
    textbutton "Malay"
    textbutton "Hebrew"
    textbutton "Back to Menu"
    textbutton "Return to Game"
    textbutton "Continue Game"
    textbutton "Load Game"
    textbutton "Save Game"
    textbutton "Quick Save"
    textbutton "Quick Load"
    textbutton "Auto Save"
    textbutton "Auto Load"
    textbutton "Settings"
    textbutton "Options"
    textbutton "Preferences"
    textbutton "Help"
    textbutton "Credits"
    textbutton "About"
    textbutton "Exit"
    textbutton "Close"
    textbutton "Open"
    textbutton "Apply"
    textbutton "Reset"
    textbutton "Default"
    textbutton "Fullscreen"
    textbutton "Windowed"
    textbutton "Sound"
    textbutton "Voice"
    textbutton "Music"
    textbutton "Display"
    textbutton "Screen"
    textbutton "Resolution"
    textbutton "Brightness"
    textbutton "Contrast"
    textbutton "Gamma"
    textbutton "Saturation"
    textbutton "Sharpness"
    textbutton "Language"
    textbutton "English"
    textbutton "Turkish"
    textbutton "Japanese"
    textbutton "Korean"
    textbutton "Chinese"
    textbutton "Spanish"
    textbutton "French"
    textbutton "German"
    textbutton "Italian"
    textbutton "Russian"
    textbutton "Polish"
    textbutton "Portuguese"
    textbutton "Czech"
    textbutton "Romanian"
    textbutton "Hungarian"
    textbutton "Greek"
    textbutton "Bulgarian"
    textbutton "Ukrainian"
    textbutton "Indonesian"
    textbutton "Malay"
    textbutton "Hebrew"
    textbutton "Back to Menu"
    textbutton "Return to Game"
    textbutton "Continue Game"
    textbutton "Load Game"
    textbutton "Save Game"
    textbutton "Quick Save"
    textbutton "Quick Load"
    textbutton "Auto Save"
    textbutton "Auto Load"
