# Real Ren'Py Translation Example - OLD_NEW Format
# Language: Turkish (tr)  
# Generated by RenLocalizer-V2

translate tr start_hello:
    old "Hello, welcome to my game!"
    new "Merhaba, oyunuma hoş geldin!"

translate tr start_name_question:
    old "What's your name?"
    new "Adın ne?"

translate tr character_introduction:
    old "Nice to meet you, [player_name]!"
    new "Tanıştığımıza memnun oldum, [player_name]!"

translate tr menu_choice_1:
    old "I want to explore"
    new "Keşfetmek istiyorum"

translate tr menu_choice_2:
    old "I want to rest"
    new "Dinlenmek istiyorum"

translate tr narrator_description:
    old "You walk into a beautiful garden."
    new "Güzel bir bahçeye giriyorsun."
