# Real Ren'Py Translation Example - SIMPLE Format
# Language: Turkish (tr)
# Generated by RenLocalizer-V2

translate tr start_hello:
    # "Hello, welcome to my game!"
    "Merhaba, oyunuma hoş geldin!"

translate tr start_name_question:
    # "What's your name?"
    "Adın ne?"

translate tr character_introduction:
    # "Nice to meet you, [player_name]!"
    "Tanıştığımıza memnun oldum, [player_name]!"

translate tr menu_choice_1:
    # "I want to explore"
    "Keşfetmek istiyorum"

translate tr menu_choice_2:
    # "I want to rest"
    "Dinlenmek istiyorum"

translate tr narrator_description:
    # "You walk into a beautiful garden."
    "Güzel bir bahçeye giriyorsun."
